#user inputs
name = input("Your name is: ")
adj = input("Describe yourself in one word: ")
noun = input("Describe yourself in a noun: ")
noun2 = input("Noun: ")
noun3 = input("Noun: ")
emotion = input("What you're feeling right now: ")
noun4 = input("Noun: ")
color = input("Pick a color: ")
puppet = input("Name one of the most famous puppets: ")
ride = input("Your favorite ride at a theme park: ")
adj2 = input("Adjective: ")
noun5 = input("Noun: ")
adj2 = input("Adjective: ")
loc = input("Where: ")
hero = input("Who's your favorite hero: ")
phrase = input("Name a quote from your hero: ")
pronoun = input("Hero's pronoun is: ")
thing = input("name an item: ")
pp = input("Hero's possessive pronoun: ")
loc2 = input("Where: ")
thing2 = input("Another item to name: ")
noun6 = input("Noun: ")
noun7 = input("Noun: ")
fe = input("Describe your feelings with a facial expression: ")
verb = input("Verb: ")
think = input("Your thought(s): ")

print("Title: Terrible (or Not?) Flight Experience")
print("Imagine that",name,"was a",adj,noun,"who encountered a flight that could only be described as a 'flying",noun2,"of",noun3,".' As soon as you boarded the plane, things just went downhill.")
print("The",emotion,"in your eyes grew as you watched the plane prepare for takeoff as you walked towards the gate. The journey you were about to embark on would lead to",noun4,".")
print("Boarding the plane, you noticed the flight crew looked a bit odd. Their uniforms were",color,
    ", and the captain looked like a",puppet,". As you sat down, you thought, 'This'll be interesting.'")
print("As soon as the engines fired up, severe turbulence hit. Your heart raced as you felt tossed around like a ragdoll. Passengers were thrown in all directions throughout the plane, as if they were on a",ride,".")
print("Flight crew members tried to calm panicked passengers with their trademark",puppet,
    "enthusiasm. You heard them say, 'Ladies and gentlemen, please remain",noun5,"and enjoy the ride! It's all part of the",adj2,"in-flight entertainment!")
print("As if things couldn't get any crazier, the plane made a surprise landing. As soon as the seat belt sign went off, everybody got up and started gatherng their stuff.")
print("You looked out the window and couldn't belive what you saw. The plane landed on a",loc,"instead of a smooth runaway. Panic set in as passengers wondered what has happened and how they were going to get off.")
print("Suddenly, a group of mountain climbers showed up. It was led by your hero,",hero,".")
print(hero,", always up for an adventure, calmly assessed the situation. 'Don't worry, ladies and gentlemen,",phrase,"!",pronoun,"said as",pronoun,"strapped on",pp,"",thing,".")
print("They guided the plane down the",loc2,"using",thing2,"and",noun6,". The passengers cheered and clapped, amazed.")
print("After what semed like an eternity, the plane reached the runaway. The passengers cheered, relieved to have made it through the unexpected trip.")
print("You couldn't help but reflect on the absurdity of your whole flight experience as you disembarked. Knowing that you'd never",noun7,"the time you flew on a 'flying",noun2,"of",noun3,", you couldn't help but",fe,".")
print("As a result, you walked off the plane with an",verb,"for the unexpected twists and turns life can sometimes throw at you. I couldn't help but wonder, '",think,"'")
